import Head from "next/head";
import Image from "next/image";
import { Author } from "@/components/atoms/Author/Author";
import { BenefitList } from "@/components/atoms/BenefitList/BenefitList";
import { Button } from "@/components/atoms/Button/Button";
import { Card } from "@/components/atoms/Card/Card";
import { Heading } from "@/components/atoms/Heading/Heading";
import { Stats } from "@/components/atoms/Stats/Stats";
import { ToastBanner } from "@/components/atoms/ToastBanner/ToastBanner";
import { ContactForm } from "@/components/molecules/ContactForm/ContactForm";
import { Navbar } from "@/components/molecules/Navbar/Navbar";
import { HeroSection } from "@/components/sections/HeroSection";

export default function Home() {
  return (
    <>
      <Head>
        <title>Neobank</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className="mx-auto mt-20 flex w-full max-w-7xl flex-col items-center px-8 py-10 md:items-start">
        <HeroSection />
        <section className="my-20 w-full">
          <Stats
            statsList={[
              { title: "Active users", value: "3800+" },
              { title: "Trusted partners", value: "230+" },
              { title: "transactions", value: "$230M+" },
            ]}
          />
        </section>
        <div
          id="why-use-us"
          className="invisible relative top-[-120px] block"
        />
        <section className="flex flex-wrap items-center justify-center gap-10 md:justify-between">
          <div className="md:max-w-[50%]">
            <Heading visualLevel="h2" elementLevel="h2">
              You do the business, we&apos;ll handle the money.
            </Heading>
            <p className="mt-4 text-[#B3B3B3]">
              With the right platform and credit card you can earn rewards and
              track your spending in one place. Using our dashboard you can
              automate and batch tasks so sending money where it needs to go is
              effortless.
            </p>
            <Button additionalClassName="mt-8" variant="primary">
              Start now
            </Button>
          </div>
          <BenefitList
            benefitsList={[
              {
                title: "Rewards",
                description:
                  "We find you the best credit cards to maximise airmiles, promotions, and prizes.",
                iconUrl: "/assets/Star.svg",
              },
              {
                title: "100% Secured",
                description:
                  "We take proactive steps make sure your information and transactions are secure.",
                iconUrl: "/assets/ShieldDone.svg",
              },
              {
                title: "Send money, anywhere, for free",
                description:
                  "Send money with us and never worry about fees again.",
                iconUrl: "/assets/Send.svg",
              },
            ]}
          />
        </section>
        <section className="my-20 flex w-full flex-wrap items-center justify-center gap-12 md:justify-between">
          <div className="w-full max-w-[528px]">
            <div className="relative flex w-full justify-center sm:h-[400px] lg:max-w-[45%]">
              <Card
                size="small"
                additionalClassName="absolute left-[288px] top-0 z-10 hidden w-[240px] sm:block"
              >
                <div className="flex max-w-[400px] items-center gap-4">
                  <Image
                    src="/assets/PaypalIcon.svg"
                    alt="Paypal"
                    height={80}
                    width={80}
                  />
                  <div className="ml-4 flex flex-col">
                    <h3 className="text-xl font-bold text-white">Paypal</h3>
                    <p className="mt-1 text-sm text-[#B3B3B3]">Payment</p>
                  </div>
                </div>
                <div className="flex w-full items-center justify-between gap-6">
                  <div className="flex flex-col">
                    <p className="text-[#B3B3B3]">Amount</p>
                    <p className="text-xl font-bold text-white">£5000</p>
                  </div>
                  <Button
                    variant="secondary"
                    style={{
                      background:
                        "radial-gradient(64.18% 64.18% at 71.16% 35.69%, #DEF9FA 0.89%, #BEF3F5 17.23%, #9DEDF0 42.04%, #7DE7EB 55.12%, #5CE1E6 71.54%, #33BBCF 100%)",
                      WebkitBackgroundClip: "text",
                      WebkitTextFillColor: "transparent",
                    }}
                  >
                    Change
                  </Button>
                </div>
                <Button variant="primary" additionalClassName="mt-4" fullWidth>
                  Make payment
                </Button>
              </Card>

              <Card
                size="small"
                additionalClassName="left-0 top-24 w-[300px] sm:absolute"
              >
                <div className="relative">
                  <Heading visualLevel="h5" elementLevel="h3">
                    Latest transactions
                  </Heading>
                  <div className="mt-4 flex flex-col gap-4">
                    <div className="flex items-center justify-between gap-6">
                      <div className="flex items-center gap-4">
                        <Image
                          src="/assets/DribbleIcon.svg"
                          alt="Dribble Icon"
                          height={40}
                          width={40}
                        />
                        <div className="flex flex-col">
                          <p className="text-sm font-bold text-white">
                            Dribbble Pro
                          </p>
                          <p className="text-xs font-semibold capitalize text-[#B3B3B3]">
                            30 Seconds ago
                          </p>
                        </div>
                      </div>

                      <p className="text-sm font-semibold text-white">-£5000</p>
                    </div>
                    <div className="flex items-center justify-between gap-6">
                      <div className="flex items-center gap-4">
                        <Image
                          src="/assets/NetflixLogo.svg"
                          alt="Dribble Icon"
                          height={40}
                          width={40}
                        />
                        <div className="flex flex-col">
                          <p className="text-sm font-bold text-white">
                            Netflix
                          </p>
                          <p className="text-xs font-semibold capitalize text-[#B3B3B3]">
                            4 Days ago
                          </p>
                        </div>
                      </div>

                      <p className="text-sm font-semibold text-white">-£7.99</p>
                    </div>
                    <div className="flex items-center justify-between gap-6">
                      <div className="flex items-center gap-4">
                        <Image
                          src="/assets/ManulifeInsuranceLogo.svg"
                          alt="Dribble Icon"
                          height={40}
                          width={40}
                        />
                        <div className="flex flex-col">
                          <p className="text-sm font-bold text-white">
                            Manulife Insurance
                          </p>
                          <p className="text-xs font-semibold capitalize text-[#B3B3B3]">
                            5 Days ago
                          </p>
                        </div>
                      </div>

                      <p className="text-sm font-semibold text-white">
                        -£50.99
                      </p>
                    </div>
                  </div>
                  <ToastBanner additionalClassName="absolute -bottom-12 -right-12 md:-right-24">
                    <Image
                      src="/assets/GreenCheck.svg"
                      alt="Green check"
                      height={24}
                      width={24}
                      className="mr-2"
                    />
                    Your payment was successful
                  </ToastBanner>
                </div>
              </Card>
            </div>
          </div>
          <div className="lg:max-w-[40%]">
            <Heading visualLevel="h2" elementLevel="h2">
              We make it easy to see and manage your money
            </Heading>
            <p className="mt-4 text-[#B3B3B3]">
              See invoices from suppliers and pay them in part or in full with
              tools that make the process easy with a few clicks.
            </p>
          </div>
        </section>
        <section className="my-20 flex w-full flex-wrap items-center justify-center gap-12 md:justify-between">
          <div className="lg:max-w-[40%]">
            <Heading visualLevel="h2" elementLevel="h2">
              Upload your credit card in less than a minute, and discover better
              offers.
            </Heading>
            <p className="mt-4 text-[#B3B3B3]">
              Don’t like the fees your current payment provider is charging?
              Switch easily inside our platform.
            </p>
            <Button variant="primary" additionalClassName="mt-4">
              Get started
            </Button>
          </div>
          <div className="relative px-4">
            <Image
              src="/assets/ConcentricCircles.svg"
              alt="Background concentric circles"
              height={400}
              width={400}
            />
            <Card
              size="small"
              additionalClassName="hidden sm:flex z-10 absolute top-[80px] -left-6 max-w-[204px] items-center flex flex-col text-center gap-2"
            >
              <Image
                src="/assets/ScanIcon.svg"
                alt="Scan icon"
                height={36}
                width={38}
              />
              <Heading visualLevel="h5" elementLevel="h3">
                Scan Credit Cards
              </Heading>
              <p className="text-sm text-[#B3B3B3]">
                Upload a photo of your credit card and we&apos;ll do the rest.
              </p>
            </Card>
            <Card
              size="small"
              additionalClassName="absolute sm:top-[40px] w-full top-1/2 left-1/2 sm:translate-x-[unset] sm:translate-y-[unset] transform sm:left-[unset] -translate-x-1/2 -translate-y-1/2 h-fit sm:-right-6 max-w-[260px] items-center flex flex-col text-center gap-2"
            >
              <div className="flex w-full justify-between">
                <Heading visualLevel="h6" elementLevel="h3">
                  Online Analysis
                </Heading>
                <div className="flex items-center">
                  <p className="text-sm text-white">12 Months</p>
                  <Image
                    src="/assets/ArrowDown.svg"
                    alt="Arrow down"
                    height={16}
                    width={16}
                  />
                </div>
              </div>
              <div className="flex w-full justify-between">
                <div className="text-left text-sm font-semibold">
                  <p className="text-[#00D2AA]">£ 2,334,67</p>
                  <p className="text-[#00D2AA] opacity-70">Income</p>
                </div>
                <div className="text-right text-sm font-semibold">
                  <p className="text-[#00D9F5]">£ 5.31M</p>
                  <p className="text-[#00D9F5] opacity-70">Expenses</p>
                </div>
              </div>
              <div className="relative h-[72px] w-full">
                <Image src="/assets/LineChart.svg" alt="Line chart" fill />
              </div>
              <div className="flex h-6 w-full items-center justify-between text-xs text-[#B3B3B3]">
                <p>Jan</p>
                <p>Feb</p>
                <div className="from-95% rounded-lg bg-gradient-to-r from-[#00D2AA] to-[#00D9F5] p-1 text-[#14101D]">
                  <p>Mar</p>
                </div>
                <p>Apr</p>
                <p>May</p>
                <p>Jun</p>
                <p>Jul</p>
              </div>
            </Card>
            <Card
              size="small"
              additionalClassName="absolute hidden sm:flex -bottom-6 left-[20%]"
            >
              <div className="flex w-full flex-col gap-3">
                <Heading visualLevel="h6" elementLevel="h3">
                  Payment Methods Available
                </Heading>
                <ul className="flex w-full justify-center gap-3">
                  <li className="relative flex h-[34px] w-[38px] items-center justify-center rounded-md bg-white">
                    <Image
                      src="/assets/PaypalLogo.svg"
                      alt="Paypal logo"
                      height={18}
                      width={20}
                    />
                  </li>
                  <li className="relative flex h-[34px] w-[38px] items-center justify-center rounded-md bg-white">
                    <Image
                      src="/assets/AppleLogo.svg"
                      alt="Apple logo"
                      height={18}
                      width={20}
                    />
                  </li>
                  <li className="relative flex h-[34px] w-[38px] items-center justify-center rounded-md bg-white">
                    <Image
                      src="/assets/VisaLogo.svg"
                      alt="Visa logo"
                      height={24}
                      width={27}
                    />
                  </li>
                  <li className="relative flex h-[34px] w-[38px] items-center justify-center rounded-md bg-white">
                    <Image
                      src="/assets/ShopifyLogo.svg"
                      alt="Shopify logo"
                      height={26}
                      width={30}
                    />
                  </li>
                </ul>
              </div>
            </Card>
          </div>
        </section>
        <div
          id="testimonials"
          className="invisible relative top-[-120px] block"
        />
        <section className="my-20 flex w-full flex-col gap-8">
          <div>
            <Heading visualLevel="h2" elementLevel="h2">
              What people are saying about us
            </Heading>
          </div>
          <div className="flex flex-wrap justify-center gap-8">
            <Card
              size="medium"
              additionalClassName="flex flex-col w-[280px] gap-8"
            >
              <Image
                src="/assets/QuoteMark.svg"
                alt="Quote mark"
                width={40}
                height={28}
              />
              <p className="text-lg font-medium text-white">
                Money is only a tool. It will take you wherever you wish, but it
                will not replace you as the driver.
              </p>
              <Author
                authorName="Janet Jensen"
                jobTitle="Product Manager"
                avatarImageUrl="/assets/JanetJensenAvatar.svg"
              />
            </Card>
            <Card
              size="medium"
              additionalClassName="flex flex-col w-[280px] gap-8"
            >
              <Image
                src="/assets/QuoteMark.svg"
                alt="Quote mark"
                width={40}
                height={28}
              />
              <p className="text-lg font-medium text-white">
                Money makes your life easier. If you&apos;re lucky to have it,
                you&apos;re lucky.
              </p>
              <Author
                authorName="Steve Mark"
                jobTitle="Founder & Leader"
                avatarImageUrl="/assets/SteveMarkAvatar.svg"
              />
            </Card>
            <Card
              size="medium"
              additionalClassName="flex flex-col w-[280px] gap-8"
            >
              <Image
                src="/assets/QuoteMark.svg"
                alt="Quote mark"
                width={40}
                height={28}
              />
              <p className="text-lg font-medium text-white">
                It is usually people in the money business, finance, and
                international trade that are really rich.
              </p>
              <Author
                authorName="Kenn Gallagher"
                jobTitle="Head of Design"
                avatarImageUrl="/assets/KennGallagherAvatar.svg"
              />
            </Card>
          </div>
        </section>
        <section className="my-20 w-full">
          <ul className="flex w-full flex-wrap justify-center gap-8">
            <li className="relative h-10 w-40">
              <Image src="/assets/AirbnbDarkLogo.svg" alt="Airbnb logo" fill />
            </li>
            <li className="relative h-10 w-40">
              <Image
                src="/assets/BinanceDarkLogo.svg"
                alt="Binance logo"
                fill
              />
            </li>
            <li className="relative h-10 w-40">
              <Image
                src="/assets/CoinbaseDarkLogo.svg"
                alt="Coinbase logo"
                fill
              />
            </li>
            <li className="relative h-10 w-40">
              <Image
                src="/assets/DropboxDarkLogo.svg"
                alt="Dropbox logo"
                fill
              />
            </li>
          </ul>
        </section>
        <div id="download" className="invisible relative top-[-120px] block" />
        <section className="my-20 w-full">
          <Card
            size="medium"
            additionalClassName="flex flex-col md:flex-row justify-between w-full items-center gap-8"
          >
            <div className="lg:max-w-[60%]">
              <Heading visualLevel="h2" elementLevel="h3">
                Download the app now!
              </Heading>
              <p className="mt-4 text-xl text-white/70">
                Everything you need to accept card payments and grow your
                business anywhere on the planet.
              </p>
            </div>
            <div className="flex w-full flex-col items-center lg:max-w-[40%]">
              <Button variant="primary">Download</Button>
              <div className="mt-6 flex flex-wrap justify-center gap-4  ">
                <Image
                  src="/assets/AppStoreLogo.svg"
                  alt="App Store logo"
                  width={118}
                  height={44}
                />
                <Image
                  src="/assets/GooglePlayLogo.svg"
                  alt="Google Play logo"
                  width={132}
                  height={44}
                />
              </div>
            </div>
          </Card>
        </section>
        <div
          id="get-in-touch"
          className="invisible relative top-[-120px] block"
        />
        <section className="my-20 flex w-full flex-col">
          <Heading visualLevel="h2" elementLevel="h2">
            Get in touch
          </Heading>
          <p className="mt-4 text-xl text-white/70">
            Have a question? Let us know and we will get back you with answers
            as soon as possible
          </p>
          <ContactForm />
        </section>
        <footer className="w-full">
          <div className="flex flex-col items-center justify-center gap-8 md:items-start">
            <Image
              src="/assets/NeobankLogo.svg"
              alt="Neobank logo"
              width={260}
              height={72}
            />
            <p className="text-center text-white/70">
              A new way to manage money
            </p>
            <div
              role="presentation"
              className="h-1 w-full border-t border-solid border-[#3F3E45]"
            />
            <div className="flex flex-col items-center justify-center gap-3 md:items-start">
              <p className="text-white/70">Copyright ©</p>
              <p className="text-white/70">
                2023 NeoBank. All Rights Reserved.
              </p>
            </div>
          </div>
        </footer>
      </main>
    </>
  );
}
